// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAccount = "account"

// Account mapped from table <account>
type Account struct {
	ID          string     `gorm:"column:id;type:varchar(80);primaryKey" json:"id"`
	ClientHost  *string    `gorm:"column:client_host;type:varchar(50)" json:"client_host"`
	UserAgent   *string    `gorm:"column:user_agent;type:varchar(512)" json:"user_agent"`
	Fingerprint *string    `gorm:"column:fingerprint;type:varchar(64)" json:"fingerprint"`
	Status      *string    `gorm:"column:status;type:varchar(50)" json:"status"`
	Openid      *string    `gorm:"column:openid;type:varchar(100)" json:"openid"`
	SessionKey  *string    `gorm:"column:session_key;type:varchar(200)" json:"session_key"`
	PhoneNumber *string    `gorm:"column:phone_number;type:varchar(20)" json:"phone_number"`
	Password    *string    `gorm:"column:password;type:varchar(300)" json:"password"`
	CreateTime  *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime  *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
	Points      *int32     `gorm:"column:points;type:int;comment:积分" json:"points"`                  // 积分
	UserName    *string    `gorm:"column:user_name;type:varchar(100);comment:用户昵称" json:"user_name"` // 用户昵称
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
