// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAccountSetting = "account_settings"

// AccountSetting mapped from table <account_settings>
type AccountSetting struct {
	ID                int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	AccountID         string     `gorm:"column:account_id;type:varchar(80);not null" json:"account_id"`
	SourceLanguage    string     `gorm:"column:source_language;type:varchar(80);not null" json:"source_language"`
	TargetLanguage    string     `gorm:"column:target_language;type:varchar(80);not null" json:"target_language"`
	SpeechRoleName    *string    `gorm:"column:speech_role_name;type:varchar(80)" json:"speech_role_name"`
	AutoPlayingVoice  *int32     `gorm:"column:auto_playing_voice;type:int" json:"auto_playing_voice"`
	PlayingVoiceSpeed *string    `gorm:"column:playing_voice_speed;type:varchar(50)" json:"playing_voice_speed"`
	AutoTextShadow    *int32     `gorm:"column:auto_text_shadow;type:int" json:"auto_text_shadow"`
	AutoPronunciation *int32     `gorm:"column:auto_pronunciation;type:int" json:"auto_pronunciation"`
	CreateTime        *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime        *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName AccountSetting's table name
func (*AccountSetting) TableName() string {
	return TableNameAccountSetting
}
