// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAccountTopic = "account_topic"

// AccountTopic mapped from table <account_topic>
type AccountTopic struct {
	ID         string     `gorm:"column:id;type:varchar(80);primaryKey" json:"id"`
	Language   string     `gorm:"column:language;type:varchar(80);not null" json:"language"`
	AiRole     string     `gorm:"column:ai_role;type:varchar(280);not null" json:"ai_role"`
	MyRole     string     `gorm:"column:my_role;type:varchar(280);not null" json:"my_role"`
	Topic      string     `gorm:"column:topic;type:varchar(2500);not null" json:"topic"`
	AccountID  string     `gorm:"column:account_id;type:varchar(80);not null" json:"account_id"`
	CreatedBy  string     `gorm:"column:created_by;type:varchar(80);not null" json:"created_by"`
	CreateTime *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	Sequence   int32      `gorm:"column:sequence;type:int;not null" json:"sequence"`
}

// TableName AccountTopic's table name
func (*AccountTopic) TableName() string {
	return TableNameAccountTopic
}
