// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAlembicVersion = "alembic_version"

// AlembicVersion mapped from table <alembic_version>
type AlembicVersion struct {
	VersionNum string `gorm:"column:version_num;type:varchar(32);primaryKey" json:"version_num"`
}

// TableName AlembicVersion's table name
func (*AlembicVersion) TableName() string {
	return TableNameAlembicVersion
}
