// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameFileDetail = "file_detail"

// FileDetail mapped from table <file_detail>
type FileDetail struct {
	ID         string     `gorm:"column:id;type:varchar(80);primaryKey" json:"id"`
	FilePath   string     `gorm:"column:file_path;type:varchar(150);not null" json:"file_path"`
	Module     *string    `gorm:"column:module;type:varchar(80)" json:"module"`
	ModuleID   *string    `gorm:"column:module_id;type:varchar(80)" json:"module_id"`
	FileName   *string    `gorm:"column:file_name;type:varchar(150)" json:"file_name"`
	FileExt    *string    `gorm:"column:file_ext;type:varchar(20)" json:"file_ext"`
	Deleted    *int32     `gorm:"column:deleted;type:int" json:"deleted"`
	CreatedBy  string     `gorm:"column:created_by;type:varchar(80);not null" json:"created_by"`
	CreateTime *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
}

// TableName FileDetail's table name
func (*FileDetail) TableName() string {
	return TableNameFileDetail
}
