// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameLesson = "lesson"

// Lesson mapped from table <lesson>
type Lesson struct {
	ID         int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Title      string     `gorm:"column:title;type:varchar(200);not null" json:"title"`
	CreateTime *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
	BookID     string     `gorm:"column:book_id;type:varchar(80);not null" json:"book_id"`
	ParentID   *string    `gorm:"column:parent_id;type:varchar(80)" json:"parent_id"`
	LessonID   string     `gorm:"column:lesson_id;type:varchar(80);not null" json:"lesson_id"`
}

// TableName Lesson's table name
func (*Lesson) TableName() string {
	return TableNameLesson
}
