// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameLessonSentence = "lesson_sentence"

// LessonSentence mapped from table <lesson_sentence>
type LessonSentence struct {
	ID         int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	LessonID   int32      `gorm:"column:lesson_id;type:int;not null" json:"lesson_id"`
	English    string     `gorm:"column:english;type:text;not null" json:"english"`
	Chinese    string     `gorm:"column:chinese;type:text;not null" json:"chinese"`
	AudioURL   *string    `gorm:"column:audio_url;type:varchar(500)" json:"audio_url"`
	AudioStart *int32     `gorm:"column:audio_start;type:int" json:"audio_start"`
	AudioEnd   *int32     `gorm:"column:audio_end;type:int" json:"audio_end"`
	IsLock     *int32     `gorm:"column:is_lock;type:int" json:"is_lock"`
	CreateTime *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName LessonSentence's table name
func (*LessonSentence) TableName() string {
	return TableNameLessonSentence
}
