// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameMessageGrammar = "message_grammar"

// MessageGrammar mapped from table <message_grammar>
type MessageGrammar struct {
	ID         int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	SessionID  string     `gorm:"column:session_id;type:varchar(80);not null" json:"session_id"`
	MessageID  string     `gorm:"column:message_id;type:varchar(80);not null" json:"message_id"`
	FileName   *string    `gorm:"column:file_name;type:varchar(80)" json:"file_name"`
	AccountID  string     `gorm:"column:account_id;type:varchar(80);not null" json:"account_id"`
	Type       string     `gorm:"column:type;type:varchar(80);not null" json:"type"`
	Result     string     `gorm:"column:result;type:text;not null" json:"result"`
	CreateTime *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
}

// TableName MessageGrammar's table name
func (*MessageGrammar) TableName() string {
	return TableNameMessageGrammar
}
