// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameMessageTranslate = "message_translate"

// MessageTranslate mapped from table <message_translate>
type MessageTranslate struct {
	ID             int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	SessionID      string     `gorm:"column:session_id;type:varchar(80);not null" json:"session_id"`
	MessageID      string     `gorm:"column:message_id;type:varchar(80);not null" json:"message_id"`
	AccountID      string     `gorm:"column:account_id;type:varchar(80);not null" json:"account_id"`
	SourceLanguage string     `gorm:"column:source_language;type:varchar(80);not null" json:"source_language"`
	TargetLanguage string     `gorm:"column:target_language;type:varchar(80);not null" json:"target_language"`
	SourceText     string     `gorm:"column:source_text;type:varchar(512);not null" json:"source_text"`
	TargetText     string     `gorm:"column:target_text;type:varchar(512);not null" json:"target_text"`
	CreateTime     *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
}

// TableName MessageTranslate's table name
func (*MessageTranslate) TableName() string {
	return TableNameMessageTranslate
}
