// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameMessage = "message"

// Message mapped from table <message>
type Message struct {
	ID         string     `gorm:"column:id;type:varchar(80);primaryKey" json:"id"`
	SessionID  string     `gorm:"column:session_id;type:varchar(80);not null" json:"session_id"`
	AccountID  string     `gorm:"column:account_id;type:varchar(80);not null" json:"account_id"`
	Sender     string     `gorm:"column:sender;type:varchar(80);not null" json:"sender"`
	Receiver   string     `gorm:"column:receiver;type:varchar(80);not null" json:"receiver"`
	Type       string     `gorm:"column:type;type:varchar(50);not null" json:"type"`
	Content    string     `gorm:"column:content;type:varchar(2500);not null" json:"content"`
	Style      *string    `gorm:"column:style;type:varchar(80)" json:"style"`
	Length     int32      `gorm:"column:length;type:int;not null" json:"length"`
	FileName   *string    `gorm:"column:file_name;type:varchar(800)" json:"file_name"`
	CreateTime *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	Deleted    *int32     `gorm:"column:deleted;type:int" json:"deleted"`
	Sequence   int32      `gorm:"column:sequence;type:int;not null" json:"sequence"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
