// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameSettingsLanguageExample = "settings_language_example"

// SettingsLanguageExample mapped from table <settings_language_example>
type SettingsLanguageExample struct {
	ID         string     `gorm:"column:id;type:varchar(80);primaryKey" json:"id"`
	Language   string     `gorm:"column:language;type:varchar(80);not null" json:"language"`
	Example    *string    `gorm:"column:example;type:varchar(250)" json:"example"`
	CreateTime *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName SettingsLanguageExample's table name
func (*SettingsLanguageExample) TableName() string {
	return TableNameSettingsLanguageExample
}
