// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameSettingsLanguage = "settings_language"

// SettingsLanguage mapped from table <settings_language>
type SettingsLanguage struct {
	ID           string     `gorm:"column:id;type:varchar(80);primaryKey" json:"id"`
	Language     string     `gorm:"column:language;type:varchar(80);not null" json:"language"`
	FullLanguage string     `gorm:"column:full_language;type:varchar(80);not null" json:"full_language"`
	Label        string     `gorm:"column:label;type:varchar(80);not null" json:"label"`
	FullLabel    string     `gorm:"column:full_label;type:varchar(80);not null" json:"full_label"`
	Description  *string    `gorm:"column:description;type:varchar(250)" json:"description"`
	Sequence     *int32     `gorm:"column:sequence;type:int" json:"sequence"`
	CreateTime   *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime   *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName SettingsLanguage's table name
func (*SettingsLanguage) TableName() string {
	return TableNameSettingsLanguage
}
