// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameStudyWordProgress = "study_word_progress"

// StudyWordProgress mapped from table <study_word_progress>
type StudyWordProgress struct {
	ID             int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	UserID         string     `gorm:"column:user_id;type:varchar(50);not null;comment:用户ID" json:"user_id"`                 // 用户ID
	WordID         int32      `gorm:"column:word_id;type:int;not null;comment:单词ID" json:"word_id"`                         // 单词ID
	BookID         string     `gorm:"column:book_id;type:varchar(50);not null;comment:书籍ID" json:"book_id"`                 // 书籍ID
	PlanID         int32      `gorm:"column:plan_id;type:int;not null;comment:计划ID" json:"plan_id"`                         // 计划ID
	LearningCount  *int32     `gorm:"column:learning_count;type:int;comment:累计学习次数" json:"learning_count"`                  // 累计学习次数
	CorrectCount   *int32     `gorm:"column:correct_count;type:int;comment:正确次数（用户答对次数）" json:"correct_count"`              // 正确次数（用户答对次数）
	IncorrectCount *int32     `gorm:"column:incorrect_count;type:int;comment:错误次数（用户答错次数）" json:"incorrect_count"`          // 错误次数（用户答错次数）
	LastStudyTime  *time.Time `gorm:"column:last_study_time;type:datetime;comment:最后一次学习时间" json:"last_study_time"`         // 最后一次学习时间
	NextReviewTime *time.Time `gorm:"column:next_review_time;type:datetime;comment:下次复习时间（未掌握时有效）" json:"next_review_time"` // 下次复习时间（未掌握时有效）
	IsMastered     *int32     `gorm:"column:is_mastered;type:int;comment:是否已掌握（0=未掌握，1=已掌握）" json:"is_mastered"`            // 是否已掌握（0=未掌握，1=已掌握）
	StudyDate      *time.Time `gorm:"column:study_date;type:date;comment:学习日期" json:"study_date"`                           // 学习日期
	Type           *int32     `gorm:"column:type;type:int;comment:单词类型（0=没全部学完模式，1=全部学完三种模式）" json:"type"`                  // 单词类型（0=没全部学完模式，1=全部学完三种模式）
	CreateTime     *time.Time `gorm:"column:create_time;type:datetime;comment:创建时间" json:"create_time"`                     // 创建时间
	UpdateTime     *time.Time `gorm:"column:update_time;type:datetime;comment:更新时间" json:"update_time"`                     // 更新时间
}

// TableName StudyWordProgress's table name
func (*StudyWordProgress) TableName() string {
	return TableNameStudyWordProgress
}
