// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameStudyPlan = "study_plans"

// StudyPlan mapped from table <study_plans>
type StudyPlan struct {
	ID         int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	UserID     string     `gorm:"column:user_id;type:varchar(50);not null;comment:用户ID" json:"user_id"` // 用户ID
	BookID     string     `gorm:"column:book_id;type:varchar(50);not null;comment:书籍ID" json:"book_id"` // 书籍ID
	DailyWords *int32     `gorm:"column:daily_words;type:int;comment:计划每天学多少个单词" json:"daily_words"`    // 计划每天学多少个单词
	CreateTime *time.Time `gorm:"column:create_time;type:datetime;comment:创建时间" json:"create_time"`     // 创建时间
	UpdateTime *time.Time `gorm:"column:update_time;type:datetime;comment:更新时间" json:"update_time"`     // 更新时间
}

// TableName StudyPlan's table name
func (*StudyPlan) TableName() string {
	return TableNameStudyPlan
}
