// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameStudyRecord = "study_records"

// StudyRecord mapped from table <study_records>
type StudyRecord struct {
	ID          int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:记录唯一标识" json:"id"` // 记录唯一标识
	UserID      string     `gorm:"column:user_id;type:varchar(50);not null;comment:用户ID" json:"user_id"`      // 用户ID
	BookID      string     `gorm:"column:book_id;type:varchar(50);not null;comment:书籍ID" json:"book_id"`      // 书籍ID
	StudyDate   time.Time  `gorm:"column:study_date;type:date;not null;comment:学习日期" json:"study_date"`       // 学习日期
	NewWords    *int32     `gorm:"column:new_words;type:int;comment:今日新学单词数" json:"new_words"`                // 今日新学单词数
	ReviewWords *int32     `gorm:"column:review_words;type:int;comment:今日复习单词数" json:"review_words"`          // 今日复习单词数
	Duration    *int32     `gorm:"column:duration;type:int;comment:今日学习时长（分钟）" json:"duration"`               // 今日学习时长（分钟）
	UpdateTime  *time.Time `gorm:"column:update_time;type:datetime;comment:更新时间" json:"update_time"`          // 更新时间
	CreateTime  *time.Time `gorm:"column:create_time;type:datetime;comment:创建时间" json:"create_time"`          // 创建时间
}

// TableName StudyRecord's table name
func (*StudyRecord) TableName() string {
	return TableNameStudyRecord
}
