// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSyllable = "syllables"

// Syllable mapped from table <syllables>
type Syllable struct {
	ID        int32   `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:音节ID" json:"id"` // 音节ID
	Letter    string  `gorm:"column:letter;type:varchar(50);not null;comment:音节对应的字母组合" json:"letter"` // 音节对应的字母组合
	Content   string  `gorm:"column:content;type:varchar(50);not null;comment:音节内容" json:"content"`    // 音节内容
	SoundPath *string `gorm:"column:sound_path;type:varchar(500);comment:音节发音音频路径" json:"sound_path"`  // 音节发音音频路径
	Phonetic  *string `gorm:"column:phonetic;type:varchar(50);comment:音节音标" json:"phonetic"`           // 音节音标
}

// TableName Syllable's table name
func (*Syllable) TableName() string {
	return TableNameSyllable
}
