// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameSysDictType = "sys_dict_type"

// SysDictType mapped from table <sys_dict_type>
type SysDictType struct {
	ID         int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	DictType   string     `gorm:"column:dict_type;type:varchar(80);not null" json:"dict_type"`
	DictName   string     `gorm:"column:dict_name;type:varchar(80);not null" json:"dict_name"`
	Status     string     `gorm:"column:status;type:varchar(80);not null" json:"status"`
	CreateTime *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName SysDictType's table name
func (*SysDictType) TableName() string {
	return TableNameSysDictType
}
