// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameSysDictDatum = "sys_dict_data"

// SysDictDatum mapped from table <sys_dict_data>
type SysDictDatum struct {
	ID         int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	DictType   string     `gorm:"column:dict_type;type:varchar(80);not null" json:"dict_type"`
	DictLabel  string     `gorm:"column:dict_label;type:varchar(80);not null" json:"dict_label"`
	DictValue  string     `gorm:"column:dict_value;type:varchar(80);not null" json:"dict_value"`
	Status     string     `gorm:"column:status;type:varchar(80);not null" json:"status"`
	CreateTime *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName SysDictDatum's table name
func (*SysDictDatum) TableName() string {
	return TableNameSysDictDatum
}
