// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameSysFeedback = "sys_feedback"

// SysFeedback mapped from table <sys_feedback>
type SysFeedback struct {
	ID         int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	AccountID  string     `gorm:"column:account_id;type:varchar(80);not null" json:"account_id"`
	Content    string     `gorm:"column:content;type:varchar(2500);not null" json:"content"`
	Contact    string     `gorm:"column:contact;type:varchar(250);not null" json:"contact"`
	CreateTime *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
}

// TableName SysFeedback's table name
func (*SysFeedback) TableName() string {
	return TableNameSysFeedback
}
