// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameSysCache = "sys_cache"

// SysCache mapped from table <sys_cache>
type SysCache struct {
	ID         int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Key        string     `gorm:"column:key;type:varchar(80);not null" json:"key"`
	Value      string     `gorm:"column:value;type:varchar(512);not null" json:"value"`
	CreateTime *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName SysCache's table name
func (*SysCache) TableName() string {
	return TableNameSysCache
}
