// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTaskTarget = "task_target"

// TaskTarget mapped from table <task_target>
type TaskTarget struct {
	ID          int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	InfoCn      string     `gorm:"column:info_cn;type:varchar(200);not null" json:"info_cn"`
	InfoEn      *string    `gorm:"column:info_en;type:varchar(200)" json:"info_en"`
	LessonID    string     `gorm:"column:lesson_id;type:varchar(500);not null" json:"lesson_id"`
	InfoEnAudio *string    `gorm:"column:info_en_audio;type:varchar(500)" json:"info_en_audio"`
	MatchType   int32      `gorm:"column:match_type;type:int;not null" json:"match_type"`
	Status      *int32     `gorm:"column:status;type:int" json:"status"`
	CreateTime  *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime  *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName TaskTarget's table name
func (*TaskTarget) TableName() string {
	return TableNameTaskTarget
}
