// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTextbook = "textbook"

// Textbook mapped from table <textbook>
type Textbook struct {
	ID          string     `gorm:"column:id;type:varchar(80);primaryKey" json:"id"`
	Name        string     `gorm:"column:name;type:varchar(200);not null" json:"name"`
	SubjectID   int32      `gorm:"column:subject_id;type:int;not null" json:"subject_id"`
	VersionType string     `gorm:"column:version_type;type:varchar(50);not null" json:"version_type"`
	Publisher   string     `gorm:"column:publisher;type:varchar(50);not null" json:"publisher"`
	Grade       string     `gorm:"column:grade;type:varchar(50);not null" json:"grade"`
	Term        string     `gorm:"column:term;type:varchar(50);not null" json:"term"`
	IconURL     *string    `gorm:"column:icon_url;type:varchar(500)" json:"icon_url"`
	ExtID       *string    `gorm:"column:ext_id;type:varchar(200)" json:"ext_id"`
	CreateTime  *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime  *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName Textbook's table name
func (*Textbook) TableName() string {
	return TableNameTextbook
}
