// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTextbookChapter = "textbook_chapter"

// TextbookChapter mapped from table <textbook_chapter>
type TextbookChapter struct {
	ID         int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Title      string     `gorm:"column:title;type:varchar(200);not null" json:"title"`
	BookID     string     `gorm:"column:book_id;type:varchar(100);not null" json:"book_id"`
	ParentID   *int32     `gorm:"column:parent_id;type:int" json:"parent_id"`
	PageID     *int32     `gorm:"column:page_id;type:int" json:"page_id"`
	PageNo     *int32     `gorm:"column:page_no;type:int" json:"page_no"`
	CreateTime *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName TextbookChapter's table name
func (*TextbookChapter) TableName() string {
	return TableNameTextbookChapter
}
