// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTextbookSentence = "textbook_sentences"

// TextbookSentence mapped from table <textbook_sentences>
type TextbookSentence struct {
	ID                  int32    `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	BookID              string   `gorm:"column:book_id;type:varchar(80);not null" json:"book_id"`
	PageNo              int32    `gorm:"column:page_no;type:int;not null" json:"page_no"`
	Sentence            string   `gorm:"column:sentence;type:text;not null" json:"sentence"`
	IsRecite            *int32   `gorm:"column:is_recite;type:int" json:"is_recite"`
	IsAiDub             *bool    `gorm:"column:is_ai_dub;type:tinyint(1)" json:"is_ai_dub"`
	TrackContinuePlayID *string  `gorm:"column:track_continue_play_id;type:varchar(80)" json:"track_continue_play_id"`
	TrackURLSource      *string  `gorm:"column:track_url_source;type:varchar(500)" json:"track_url_source"`
	TrackRight          *float32 `gorm:"column:track_right;type:float" json:"track_right"`
	TrackTop            *float32 `gorm:"column:track_top;type:float" json:"track_top"`
	TrackLeft           *float32 `gorm:"column:track_left;type:float" json:"track_left"`
	TrackURL            *string  `gorm:"column:track_url;type:varchar(500)" json:"track_url"`
	TrackID             *int32   `gorm:"column:track_id;type:int" json:"track_id"`
	IsEvaluation        *int32   `gorm:"column:is_evaluation;type:int" json:"is_evaluation"`
	TrackName           *string  `gorm:"column:track_name;type:varchar(200)" json:"track_name"`
	TrackGenre          *string  `gorm:"column:track_genre;type:text" json:"track_genre"`
	TrackDuration       *float32 `gorm:"column:track_duration;type:float" json:"track_duration"`
	TrackIndex          int32    `gorm:"column:track_index;type:int;not null" json:"track_index"`
	TrackText           *string  `gorm:"column:track_text;type:text" json:"track_text"`
	TrackEvaluation     *string  `gorm:"column:track_evaluation;type:text" json:"track_evaluation"`
	TrackBottom         *float32 `gorm:"column:track_bottom;type:float" json:"track_bottom"`
}

// TableName TextbookSentence's table name
func (*TextbookSentence) TableName() string {
	return TableNameTextbookSentence
}
