// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTopicGroup = "topic_group"

// TopicGroup mapped from table <topic_group>
type TopicGroup struct {
	ID          string     `gorm:"column:id;type:varchar(80);primaryKey" json:"id"`
	Type        string     `gorm:"column:type;type:varchar(80);not null" json:"type"`
	Name        string     `gorm:"column:name;type:varchar(80);not null" json:"name"`
	Description string     `gorm:"column:description;type:varchar(80);not null" json:"description"`
	Status      string     `gorm:"column:status;type:varchar(80);not null" json:"status"`
	Sequence    int32      `gorm:"column:sequence;type:int;not null" json:"sequence"`
	CreatedBy   string     `gorm:"column:created_by;type:varchar(80);not null" json:"created_by"`
	CreateTime  *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime  *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName TopicGroup's table name
func (*TopicGroup) TableName() string {
	return TableNameTopicGroup
}
