// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTopicHistory = "topic_history"

// TopicHistory mapped from table <topic_history>
type TopicHistory struct {
	ID                        int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	AccountID                 string     `gorm:"column:account_id;type:varchar(80);not null" json:"account_id"`
	TopicID                   string     `gorm:"column:topic_id;type:varchar(80);not null" json:"topic_id"`
	TopicType                 string     `gorm:"column:topic_type;type:varchar(80);not null" json:"topic_type"`
	TopicName                 string     `gorm:"column:topic_name;type:varchar(80);not null" json:"topic_name"`
	MainTargetCount           int32      `gorm:"column:main_target_count;type:int;not null" json:"main_target_count"`
	TrialTargetCount          int32      `gorm:"column:trial_target_count;type:int;not null" json:"trial_target_count"`
	MainTargetCompletedCount  int32      `gorm:"column:main_target_completed_count;type:int;not null" json:"main_target_completed_count"`
	TrialTargetCompletedCount int32      `gorm:"column:trial_target_completed_count;type:int;not null" json:"trial_target_completed_count"`
	Completion                int32      `gorm:"column:completion;type:int;not null" json:"completion"`
	AudioScore                *int32     `gorm:"column:audio_score;type:int" json:"audio_score"`
	ContentScore              *int32     `gorm:"column:content_score;type:int" json:"content_score"`
	Suggestion                *string    `gorm:"column:suggestion;type:varchar(2080)" json:"suggestion"`
	WordCount                 *int32     `gorm:"column:word_count;type:int" json:"word_count"`
	SessionID                 string     `gorm:"column:session_id;type:varchar(80);not null" json:"session_id"`
	Completed                 string     `gorm:"column:completed;type:varchar(80);not null" json:"completed"`
	Status                    string     `gorm:"column:status;type:varchar(80);not null" json:"status"`
	CreateTime                *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
}

// TableName TopicHistory's table name
func (*TopicHistory) TableName() string {
	return TableNameTopicHistory
}
