// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTopicSessionRelation = "topic_session_relation"

// TopicSessionRelation mapped from table <topic_session_relation>
type TopicSessionRelation struct {
	ID         int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	TopicID    string     `gorm:"column:topic_id;type:varchar(80);not null" json:"topic_id"`
	SessionID  string     `gorm:"column:session_id;type:varchar(80);not null" json:"session_id"`
	AccountID  string     `gorm:"column:account_id;type:varchar(80);not null" json:"account_id"`
	CreateTime *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName TopicSessionRelation's table name
func (*TopicSessionRelation) TableName() string {
	return TableNameTopicSessionRelation
}
