// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTopic = "topic"

// Topic mapped from table <topic>
type Topic struct {
	ID            string     `gorm:"column:id;type:varchar(80);primaryKey" json:"id"`
	GroupID       string     `gorm:"column:group_id;type:varchar(80);not null" json:"group_id"`
	Language      string     `gorm:"column:language;type:varchar(80);not null" json:"language"`
	Name          string     `gorm:"column:name;type:varchar(80);not null" json:"name"`
	Level         int32      `gorm:"column:level;type:int;not null" json:"level"`
	RoleShortName string     `gorm:"column:role_short_name;type:varchar(80);not null" json:"role_short_name"`
	SpeechRate    string     `gorm:"column:speech_rate;type:varchar(80);not null" json:"speech_rate"`
	TopicBotName  string     `gorm:"column:topic_bot_name;type:varchar(580);not null" json:"topic_bot_name"`
	TopicUserName string     `gorm:"column:topic_user_name;type:varchar(580);not null" json:"topic_user_name"`
	Prompt        string     `gorm:"column:prompt;type:varchar(2500);not null" json:"prompt"`
	Description   string     `gorm:"column:description;type:varchar(580);not null" json:"description"`
	Status        string     `gorm:"column:status;type:varchar(80);not null" json:"status"`
	Sequence      int32      `gorm:"column:sequence;type:int;not null" json:"sequence"`
	ImageURL      *string    `gorm:"column:image_url;type:varchar(500)" json:"image_url"`
	CreatedBy     string     `gorm:"column:created_by;type:varchar(80);not null" json:"created_by"`
	CreateTime    *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime    *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName Topic's table name
func (*Topic) TableName() string {
	return TableNameTopic
}
