// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTopicPhrase = "topic_phrase"

// TopicPhrase mapped from table <topic_phrase>
type TopicPhrase struct {
	ID                int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	TopicID           string     `gorm:"column:topic_id;type:varchar(80);not null" json:"topic_id"`
	Phrase            string     `gorm:"column:phrase;type:varchar(500);not null" json:"phrase"`
	PhraseTranslation *string    `gorm:"column:phrase_translation;type:varchar(500)" json:"phrase_translation"`
	Type              string     `gorm:"column:type;type:varchar(80);not null" json:"type"`
	Status            string     `gorm:"column:status;type:varchar(80);not null" json:"status"`
	Sequence          int32      `gorm:"column:sequence;type:int;not null" json:"sequence"`
	CreatedBy         string     `gorm:"column:created_by;type:varchar(80);not null" json:"created_by"`
	CreateTime        *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime        *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName TopicPhrase's table name
func (*TopicPhrase) TableName() string {
	return TableNameTopicPhrase
}
