// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTopicTarget = "topic_target"

// TopicTarget mapped from table <topic_target>
type TopicTarget struct {
	ID                     int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	TopicID                string     `gorm:"column:topic_id;type:varchar(80);not null" json:"topic_id"`
	Type                   string     `gorm:"column:type;type:varchar(80);not null" json:"type"`
	Description            string     `gorm:"column:description;type:varchar(500);not null" json:"description"`
	DescriptionTranslation *string    `gorm:"column:description_translation;type:varchar(500)" json:"description_translation"`
	Status                 string     `gorm:"column:status;type:varchar(80);not null" json:"status"`
	Sequence               int32      `gorm:"column:sequence;type:int;not null" json:"sequence"`
	CreatedBy              string     `gorm:"column:created_by;type:varchar(80);not null" json:"created_by"`
	CreateTime             *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime             *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName TopicTarget's table name
func (*TopicTarget) TableName() string {
	return TableNameTopicTarget
}
