// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameWordSyllable = "word_syllables"

// WordSyllable mapped from table <word_syllables>
type WordSyllable struct {
	ID         int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:主键ID" json:"id"` // 主键ID
	WordID     int32      `gorm:"column:word_id;type:int;not null;comment:单词ID" json:"word_id"`            // 单词ID
	SyllableID int32      `gorm:"column:syllable_id;type:int;not null;comment:音节ID" json:"syllable_id"`    // 音节ID
	Position   int32      `gorm:"column:position;type:int;not null;comment:音节在单词中的位置" json:"position"`     // 音节在单词中的位置
	CreateTime *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
}

// TableName WordSyllable's table name
func (*WordSyllable) TableName() string {
	return TableNameWordSyllable
}
