// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameWord = "words"

// Word mapped from table <words>
type Word struct {
	ID              int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`      // 主键ID
	WordID          int32      `gorm:"column:word_id;type:int;not null;comment:单词唯一标识ID" json:"word_id"`             // 单词唯一标识ID
	LessonID        int32      `gorm:"column:lesson_id;type:int;not null;comment:所属课时ID" json:"lesson_id"`           // 所属课时ID
	BookID          string     `gorm:"column:book_id;type:varchar(50);not null;comment:所属书籍ID" json:"book_id"`       // 所属书籍ID
	Word            *string    `gorm:"column:word;type:varchar(100);comment:单词内容" json:"word"`                       // 单词内容
	Chinese         *string    `gorm:"column:chinese;type:varchar(200);comment:单词的中文释义" json:"chinese"`              // 单词的中文释义
	Phonetic        *string    `gorm:"column:phonetic;type:varchar(100);comment:单词的音标" json:"phonetic"`              // 单词的音标
	UkPhonetic      *string    `gorm:"column:uk_phonetic;type:varchar(100);comment:英式音标" json:"uk_phonetic"`         // 英式音标
	UsPhonetic      *string    `gorm:"column:us_phonetic;type:varchar(100);comment:美式音标" json:"us_phonetic"`         // 美式音标
	SoundPath       *string    `gorm:"column:sound_path;type:varchar(500);comment:单词音频文件路径" json:"sound_path"`       // 单词音频文件路径
	UkSoundPath     *string    `gorm:"column:uk_sound_path;type:varchar(500);comment:英式发音音频路径" json:"uk_sound_path"` // 英式发音音频路径
	UsSoundPath     *string    `gorm:"column:us_sound_path;type:varchar(500);comment:美式发音音频路径" json:"us_sound_path"` // 美式发音音频路径
	ImagePath       *string    `gorm:"column:image_path;type:varchar(500);comment:单词图片文件路径" json:"image_path"`       // 单词图片文件路径
	HasBase         *bool      `gorm:"column:has_base;type:tinyint(1);comment:是否包含基础词信息" json:"has_base"`            // 是否包含基础词信息
	Paraphrase      *string    `gorm:"column:paraphrase;type:text;comment:单词的详细释义" json:"paraphrase"`                // 单词的详细释义
	Phonics         *string    `gorm:"column:phonics;type:text;comment:单词的自然拼读信息" json:"phonics"`                    // 单词的自然拼读信息
	WordTense       *string    `gorm:"column:word_tense;type:text;comment:单词的不同词态（如单数、复数、过去式等）" json:"word_tense"`   // 单词的不同词态（如单数、复数、过去式等）
	ExampleSentence *string    `gorm:"column:example_sentence;type:text;comment:包含该单词的例句" json:"example_sentence"`   // 包含该单词的例句
	Phrase          *string    `gorm:"column:phrase;type:text;comment:包含该单词的常见词组" json:"phrase"`                     // 包含该单词的常见词组
	Synonym         *string    `gorm:"column:synonym;type:text;comment:单词的近义词" json:"synonym"`                       // 单词的近义词
	CreateTime      *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime      *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName Word's table name
func (*Word) TableName() string {
	return TableNameWord
}
