definitions:
  controllers.CreateTaskContentRequest:
    properties:
      content_id:
        description: 关联内容ID（可选）
        type: integer
      content_type:
        description: |-
          内容类型（dictation: 听写，sentence_repeat: 句子跟读）
          Required: true
          Enum: dictation,sentence_repeat
        type: string
      custom_content:
        description: |-
          自定义内容文本（可选，最大长度1000）
          MaxLength: 1000
        maxLength: 1000
        type: string
      difficulty:
        description: |-
          难度等级（easy/medium/hard）
          Enum: easy,medium,hard
        type: string
      order_num:
        description: |-
          排序序号（>=0）
          Required: true
          Minimum: 0
        minimum: 0
        type: integer
      points:
        description: |-
          题目分值（1-100分）
          Required: true
          Minimum: 1
          Maximum: 100
        maximum: 100
        minimum: 1
        type: integer
      ref_book_id:
        description: |-
          教材ID（generate_mode=auto时必填）
          Example: pep_english
        type: string
      ref_lesson_id:
        description: |-
          教材单元ID（generate_mode=auto时必填）
          Example: 3
        type: integer
      selected_sentence_ids:
        description: |-
          已选句子ID列表（generate_mode=manual且content_type=sentence_repeat时必填）
          Example: [101,102]
        items:
          type: integer
        type: array
      selected_word_ids:
        description: |-
          已选单词ID列表（generate_mode=manual且content_type=dictation时必填）
          Example: [1,2,3]
        items:
          type: integer
        type: array
    required:
    - content_type
    - order_num
    - points
    type: object
  controllers.CreateTaskRequest:
    properties:
      allow_late_submission:
        description: |-
          是否允许迟交（默认false）
          Example: true
        type: boolean
      contents:
        description: |-
          任务内容集合（至少包含1个内容项）
          Required: true
          MinSize: 1
        items:
          $ref: '#/definitions/controllers.CreateTaskContentRequest'
        minItems: 1
        type: array
      deadline:
        description: |-
          截止时间（当status=published时必填）
          Format: date-time
        type: string
      description:
        description: |-
          任务描述（可选，最大500字符）
          MaxLength: 500
        maxLength: 500
        type: string
      status:
        allOf:
        - $ref: '#/definitions/models.TaskStatus'
        description: |-
          任务状态（draft: 草稿，published: 已发布）
          Enum: draft,published
        enum:
        - draft
        - published
      subject:
        allOf:
        - $ref: '#/definitions/models.SubjectType'
        description: |-
          学科类型（目前仅支持english）
          Required: true
          Enum: english
      task_type:
        allOf:
        - $ref: '#/definitions/models.TaskType'
        description: |-
          任务类型（dictation: 听写，sentence_repeat: 句子跟读）
          Required: true
          Enum: dictation,sentence_repeat
      title:
        description: |-
          任务标题（必填，3-100字符）
          Required: true
          MinLength: 3
          MaxLength: 100
        maxLength: 100
        minLength: 3
        type: string
    required:
    - contents
    - subject
    - task_type
    - title
    type: object
  controllers.ListTaskResponse:
    properties:
      tasks:
        items:
          $ref: '#/definitions/controllers.TaskResponse'
        type: array
      total:
        type: integer
    type: object
  controllers.TaskContentResponse:
    properties:
      content_type:
        type: string
      id:
        type: integer
      metadata:
        description: |-
          Metadata contains structured content details
          swagger:strfmt byte
        type: object
      order_num:
        type: integer
      points:
        type: integer
    type: object
  controllers.TaskResponse:
    properties:
      contents:
        items:
          $ref: '#/definitions/controllers.TaskContentResponse'
        type: array
      created_at:
        type: string
      id:
        type: integer
      status:
        $ref: '#/definitions/models.TaskStatus'
      title:
        type: string
    type: object
  controllers.UpdateTaskRequest:
    properties:
      deadline:
        type: string
      description:
        type: string
      status:
        $ref: '#/definitions/models.TaskStatus'
      title:
        type: string
    type: object
  models.SubjectType:
    enum:
    - english
    - chinese
    - math
    - science
    - history
    - geography
    - art
    - music
    - physical_education
    - other
    type: string
    x-enum-comments:
      Art: 美术
      Chinese: 语文
      English: 英语
      Geography: 地理
      History: 历史
      Math: 数学
      Music: 音乐
      Other: 其他
      PhysicalEducation: 体育
      Science: 科学
    x-enum-varnames:
    - English
    - Chinese
    - Math
    - Science
    - History
    - Geography
    - Art
    - Music
    - PhysicalEducation
    - Other
  models.TaskStatus:
    enum:
    - draft
    - published
    - in_progress
    - completed
    - archived
    type: string
    x-enum-comments:
      Archived: 已归档
      Completed: 已完成
      Draft: 草稿
      InProgress: 进行中
      Published: 已发布
    x-enum-varnames:
    - Draft
    - Published
    - InProgress
    - Completed
    - Archived
  models.TaskType:
    enum:
    - dictation
    - spelling
    - pronunciation
    - sentence_repeat
    - quiz
    type: string
    x-enum-comments:
      Dictation: 单词听写
      Pronunciation: 发音测评
      Quiz: 测验
      SentenceRepeat: 句子跟读
      Spelling: 单词拼写
    x-enum-varnames:
    - Dictation
    - Spelling
    - Pronunciation
    - SentenceRepeat
    - Quiz
info:
  contact: {}
paths:
  /tasks:
    get:
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.ListTaskResponse'
      summary: 分页查询任务
      tags:
      - tasks
    post:
      consumes:
      - application/json
      parameters:
      - description: 任务数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controllers.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.TaskResponse'
      summary: 创建任务
      tags:
      - tasks
  /tasks/{id}:
    delete:
      parameters:
      - description: 任务ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: 删除任务
      tags:
      - tasks
    get:
      parameters:
      - description: 任务ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.TaskResponse'
      summary: 获取任务详情
      tags:
      - tasks
    put:
      consumes:
      - application/json
      parameters:
      - description: 任务ID
        in: path
        name: id
        required: true
        type: integer
      - description: 更新数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controllers.UpdateTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.TaskResponse'
      summary: 更新任务
      tags:
      - tasks
swagger: "2.0"
