"""textbook_entity updated

Revision ID: 003db9097c15
Revises: 96084c351f80
Create Date: 2025-02-16 13:48:35.984373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '003db9097c15'
down_revision: Union[str, None] = '96084c351f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('textbook', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.add_column('textbook', sa.Column('version_type', sa.String(length=50), nullable=False))
    op.add_column('textbook', sa.Column('icon_url', sa.String(length=500), nullable=True))
    op.add_column('textbook', sa.Column('ext_id', sa.String(length=200), nullable=False))
    op.drop_column('textbook', 'stage_id')
    op.drop_column('textbook', 'stage_tag')
    op.drop_column('textbook', 'term_tag')
    op.drop_column('textbook', 'grade_tag')
    op.drop_column('textbook', 'version_id')
    op.drop_column('textbook', 'version_tag')
    op.drop_column('textbook', 'has_content')
    op.drop_column('textbook', 'cover')
    op.drop_column('textbook', 'version')
    op.drop_column('textbook', 'stage')
    op.drop_column('textbook', 'user_name')
    op.drop_column('textbook', 'term_id')
    op.drop_column('textbook', 'grade_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('textbook', sa.Column('grade_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('textbook', sa.Column('term_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('textbook', sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('textbook', sa.Column('stage', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('textbook', sa.Column('version', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('textbook', sa.Column('cover', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('textbook', sa.Column('has_content', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('textbook', sa.Column('version_tag', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('textbook', sa.Column('version_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('textbook', sa.Column('grade_tag', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('textbook', sa.Column('term_tag', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('textbook', sa.Column('stage_tag', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('textbook', sa.Column('stage_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('textbook', 'ext_id')
    op.drop_column('textbook', 'icon_url')
    op.drop_column('textbook', 'version_type')
    op.drop_column('textbook', 'subject_id')
    # ### end Alembic commands ###
