"""db init1

Revision ID: 09db9db90593
Revises: 612a7f8c6e16
Create Date: 2025-02-16 17:40:50.193651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09db9db90593'
down_revision: Union[str, None] = '612a7f8c6e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('textbook_id', sa.String(length=80), nullable=True),
    sa.Column('category_id', sa.String(length=80), nullable=True),
    sa.Column('lesson_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('sub_title', sa.String(length=200), nullable=True),
    sa.Column('pic', sa.String(length=500), nullable=True),
    sa.Column('feature', sa.Integer(), nullable=True),
    sa.Column('is_audition', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('ext_id', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson')
    # ### end Alembic commands ###
