"""Change textbook_id to BigInteger

Revision ID: 0c55b2d5e64b
Revises: 1ddeb9d35a3b
Create Date: 2025-07-26 21:40:43.643656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0c55b2d5e64b'
down_revision: Union[str, None] = '1ddeb9d35a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'textbook_id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='关联教材ID',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'textbook_id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_comment='关联教材ID',
               existing_nullable=True)
    # ### end Alembic commands ###
