"""init alembic

Revision ID: 0c7db139aa8a
Revises: c97e11bffc15
Create Date: 2025-03-08 17:11:23.392339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0c7db139aa8a'
down_revision: Union[str, None] = 'c97e11bffc15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_completion_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='完成记录唯一标识'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('book_id', sa.String(length=50), nullable=False, comment='书籍ID'),
    sa.Column('date', sa.Date(), nullable=False, comment='完成日期'),
    sa.Column('status', sa.Integer(), nullable=True, comment='完成状态（0: 未完成, 1: 已完成）'),
    sa.Column('continuous_days', sa.Integer(), nullable=True, comment='连续完成天数'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_book_date', 'study_completion_records', ['user_id', 'book_id', 'date'], unique=False)
    op.create_index('idx_user_date', 'study_completion_records', ['user_id', 'date'], unique=False)
    op.alter_column('study_word_progress', 'book_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_comment='书籍ID',
               existing_nullable=False)
    op.drop_index('topic_id_index', table_name='topic_target')
    op.create_index('uq_target_topic_type_seq', 'topic_target', ['topic_id', 'type', 'sequence'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_target_topic_type_seq', table_name='topic_target')
    op.create_index('topic_id_index', 'topic_target', ['topic_id'], unique=False)
    op.alter_column('study_word_progress', 'book_id',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_comment='书籍ID',
               existing_nullable=False)
    op.drop_index('idx_user_date', table_name='study_completion_records')
    op.drop_index('idx_user_book_date', table_name='study_completion_records')
    op.drop_table('study_completion_records')
    # ### end Alembic commands ###
