"""textbook page updated

Revision ID: 1388bf576eb4
Revises: 98fcc6817f7a
Create Date: 2025-02-17 00:25:26.527804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1388bf576eb4'
down_revision: Union[str, None] = '98fcc6817f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('textbook_sentences', 'track_genre',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=1200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('textbook_sentences', 'track_genre',
               existing_type=sa.String(length=1200),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###
