"""remove index of word_id

Revision ID: 20ad4ae72919
Revises: 176619c6a6c4
Create Date: 2025-02-19 21:30:15.171945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ad4ae72919'
down_revision: Union[str, None] = '176619c6a6c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_words_word_id', table_name='words')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_words_word_id', 'words', ['word_id'], unique=True)
    # ### end Alembic commands ###
