"""description of the migration

Revision ID: 21e3a67abca6
Revises: 5f306aed4584
Create Date: 2025-01-22 02:06:43.181049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '21e3a67abca6'
down_revision: Union[str, None] = '5f306aed4584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('lesson_id', sa.String(length=80), nullable=False))
    op.alter_column('lesson', 'textbook_id',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('lesson', 'category_id',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lesson', 'category_id',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('lesson', 'textbook_id',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.drop_column('lesson', 'lesson_id')
    # ### end Alembic commands ###
