"""init alembic

Revision ID: 2661ca6df8d3
Revises: 
Create Date: 2025-03-15 17:42:24.980377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2661ca6df8d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_word_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('word_id', sa.Integer(), nullable=False, comment='单词ID'),
    sa.Column('book_id', sa.String(length=50), nullable=False, comment='书籍ID'),
    sa.Column('plan_id', sa.Integer(), nullable=False, comment='计划ID'),
    sa.Column('learning_count', sa.Integer(), nullable=True, comment='累计学习次数'),
    sa.Column('correct_count', sa.Integer(), nullable=True, comment='正确次数（用户答对次数）'),
    sa.Column('incorrect_count', sa.Integer(), nullable=True, comment='错误次数（用户答错次数）'),
    sa.Column('last_study_time', sa.DateTime(), nullable=True, comment='最后一次学习时间'),
    sa.Column('next_review_time', sa.DateTime(), nullable=True, comment='下次复习时间（未掌握时有效）'),
    sa.Column('is_mastered', sa.Integer(), nullable=True, comment='是否已掌握（0=未掌握，1=已掌握）'),
    sa.Column('study_date', sa.Date(), nullable=True, comment='学习日期'),
    sa.Column('type', sa.Integer(), nullable=True, comment='单词类型（0=没全部学完模式，1=全部学完三种模式）'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_word', 'study_word_progress', ['user_id', 'word_id'], unique=False)
    op.add_column('study_completion_records', sa.Column('points', sa.Integer(), nullable=True, comment='积分'))
    op.add_column('study_progress_reports', sa.Column('content_id', sa.Integer(), nullable=False, comment='内容ID（单词ID或句子ID等）'))
    op.add_column('study_progress_reports', sa.Column('voice_file', sa.String(length=300), nullable=True, comment='语音文件路径或 URL'))
    op.alter_column('study_progress_reports', 'content_type',
               existing_type=mysql.INTEGER(),
               comment='类型（0: 单词发音, 1: 单词读, 2: 单词写, 3: 单独拼写按钮进去的那边提交, 4:句子）',
               existing_comment='类型（0: 单词发音, 1: 单词读, 2: 单词写, 3: 句子）',
               existing_nullable=False)
    op.alter_column('study_progress_reports', 'json_data',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               comment='TEXT 数据 的评分数据',
               existing_comment='JSON 数据',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_progress_reports', 'json_data',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               comment='JSON 数据',
               existing_comment='TEXT 数据 的评分数据',
               existing_nullable=True)
    op.alter_column('study_progress_reports', 'content_type',
               existing_type=mysql.INTEGER(),
               comment='类型（0: 单词发音, 1: 单词读, 2: 单词写, 3: 句子）',
               existing_comment='类型（0: 单词发音, 1: 单词读, 2: 单词写, 3: 单独拼写按钮进去的那边提交, 4:句子）',
               existing_nullable=False)
    op.drop_column('study_progress_reports', 'voice_file')
    op.drop_column('study_progress_reports', 'content_id')
    op.drop_column('study_completion_records', 'points')
    op.drop_index('idx_user_word', table_name='study_word_progress')
    op.drop_table('study_word_progress')
    # ### end Alembic commands ###
