"""change user_id and book_id to String with length

Revision ID: 2a04458b2ddf
Revises: c41105c75e72
Create Date: 2025-03-03 12:10:20.215371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2a04458b2ddf'
down_revision: Union[str, None] = 'c41105c75e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_plans', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=50),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('study_plans', 'book_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=50),
               existing_comment='书籍ID',
               existing_nullable=False)
    op.drop_column('study_plans', 'total_days')
    op.drop_column('study_plans', 'total_words')
    op.alter_column('study_records', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=50),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('study_records', 'book_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=50),
               existing_comment='书籍ID',
               existing_nullable=False)
    op.alter_column('study_word_progress', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=50),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('study_word_progress', 'book_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=50),
               existing_comment='书籍ID',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_word_progress', 'book_id',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(display_width=11),
               existing_comment='书籍ID',
               existing_nullable=False)
    op.alter_column('study_word_progress', 'user_id',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(display_width=11),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('study_records', 'book_id',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(display_width=11),
               existing_comment='书籍ID',
               existing_nullable=False)
    op.alter_column('study_records', 'user_id',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(display_width=11),
               existing_comment='用户ID',
               existing_nullable=False)
    op.add_column('study_plans', sa.Column('total_words', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='这本书总共多少单词'))
    op.add_column('study_plans', sa.Column('total_days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='总计划天数'))
    op.alter_column('study_plans', 'book_id',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(display_width=11),
               existing_comment='书籍ID',
               existing_nullable=False)
    op.alter_column('study_plans', 'user_id',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(display_width=11),
               existing_comment='用户ID',
               existing_nullable=False)
    # ### end Alembic commands ###
