"""add lesson_id and type to study_completion_records

Revision ID: 2c6cdd02e5b1
Revises: c97e11bffc15
Create Date: 2025-03-10 10:04:11.246151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c6cdd02e5b1'
down_revision: Union[str, None] = 'c97e11bffc15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_completion_records', sa.Column('lesson_id', sa.Integer(), nullable=True, comment='课程ID'))
    op.add_column('study_completion_records', sa.Column('type', sa.Integer(), nullable=True, comment='类型（0: 单词, 1: 别的）'))
    op.drop_index('idx_user_book_date', table_name='study_completion_records')
    op.create_index('idx_user_book_date', 'study_completion_records', ['user_id', 'book_id', 'lesson_id', 'type'], unique=False)
    op.drop_index('uq_target_topic_type_seq', table_name='topic_target')
    op.create_index('topic_id_index', 'topic_target', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('topic_id_index', table_name='topic_target')
    op.create_index('uq_target_topic_type_seq', 'topic_target', ['topic_id', 'type', 'sequence'], unique=True)
    op.drop_index('idx_user_book_date', table_name='study_completion_records')
    op.create_index('idx_user_book_date', 'study_completion_records', ['user_id', 'book_id', 'date'], unique=False)
    op.drop_column('study_completion_records', 'type')
    op.drop_column('study_completion_records', 'lesson_id')
    # ### end Alembic commands ###
