"""init

Revision ID: 3290a6b81287
Revises: 
Create Date: 2025-02-16 00:08:01.156482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3290a6b81287'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('uk_phonetic', sa.String(length=100), nullable=True, comment='英式音标'))
    op.add_column('words', sa.Column('us_phonetic', sa.String(length=100), nullable=True, comment='美式音标'))
    op.add_column('words', sa.Column('uk_sound_path', sa.String(length=500), nullable=True, comment='英式发音音频路径'))
    op.add_column('words', sa.Column('us_sound_path', sa.String(length=500), nullable=True, comment='美式发音音频路径'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'us_sound_path')
    op.drop_column('words', 'uk_sound_path')
    op.drop_column('words', 'us_phonetic')
    op.drop_column('words', 'uk_phonetic')
    # ### end Alembic commands ###
