"""“修改添加字段”

Revision ID: 36a47b6a2ceb
Revises: 7a654b374509
Create Date: 2025-03-04 22:03:19.728102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36a47b6a2ceb'
down_revision: Union[str, None] = '7a654b374509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_plans', sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'))
    op.add_column('study_records', sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'))
    op.add_column('study_records', sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'))
    op.add_column('study_word_progress', sa.Column('plan_id', sa.Integer(), nullable=True, comment='学习计划ID'))
    op.add_column('study_word_progress', sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_word_progress', 'update_time')
    op.drop_column('study_word_progress', 'plan_id')
    op.drop_column('study_records', 'update_time')
    op.drop_column('study_records', 'create_time')
    op.drop_column('study_plans', 'update_time')
    # ### end Alembic commands ###
