"""添加 voice_file字段

Revision ID: 3b9f46d7dd9f
Revises: e7114820b742
Create Date: 2025-03-14 21:52:21.084168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b9f46d7dd9f'
down_revision: Union[str, None] = 'e7114820b742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_progress_reports', sa.Column('voice_file', sa.String(length=300), nullable=True, comment='语音文件路径或 URL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_progress_reports', 'voice_file')
    # ### end Alembic commands ###
