"""update textbook_sentences table structure

Revision ID: 3edfbf7848cf
Revises: 6d563d30a313
Create Date: 2025-02-17 22:19:20.535091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3edfbf7848cf'
down_revision: Union[str, None] = '6d563d30a313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('textbook_sentences', 'track_evaluation',
               existing_type=mysql.VARCHAR(length=1500),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('textbook_sentences', 'track_evaluation',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1500),
               existing_nullable=True)
    # ### end Alembic commands ###
