"""add type field to StudyWordProgress

Revision ID: 40de73aefaa7
Revises: dce2cb236b6f
Create Date: 2025-03-03 09:11:25.701396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40de73aefaa7'
down_revision: Union[str, None] = 'dce2cb236b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
