"""添加progress_data to StudyCompletionRecord

Revision ID: 522255adb2b8
Revises: d9452ca27e38
Create Date: 2025-03-25 10:41:11.746371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '522255adb2b8'
down_revision: Union[str, None] = 'd9452ca27e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_completion_records', sa.Column('progress_data', sa.Text(), nullable=True, comment='存储类似 study_progress_reports 表的数据'))
    op.alter_column('study_completion_records', 'type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='类型（0: 单词, 1: 句子,2.背词计划用了）',
               existing_comment='类型（0: 单词, 1: 别的）',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_completion_records', 'type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='类型（0: 单词, 1: 别的）',
               existing_comment='类型（0: 单词, 1: 句子,2.背词计划用了）',
               existing_nullable=True)
    op.drop_column('study_completion_records', 'progress_data')
    # ### end Alembic commands ###
