"""description of the migration

Revision ID: 5f306aed4584
Revises: 40aa6a23276c
Create Date: 2025-01-22 01:34:46.873378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5f306aed4584'
down_revision: Union[str, None] = '40aa6a23276c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_target', 'info_cn',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('task_target', 'info_en',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('task_target', 'lesson_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_target', 'lesson_id',
               existing_type=sa.String(length=500),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('task_target', 'info_en',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('task_target', 'info_cn',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
