"""db init

Revision ID: 612a7f8c6e16
Revises: c6704481cdd9
Create Date: 2025-02-16 17:35:39.176025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612a7f8c6e16'
down_revision: Union[str, None] = 'c6704481cdd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info_cn', sa.String(length=200), nullable=False),
    sa.Column('info_en', sa.String(length=200), nullable=True),
    sa.Column('lesson_id', sa.String(length=500), nullable=False),
    sa.Column('info_en_audio', sa.String(length=500), nullable=True),
    sa.Column('match_type', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_target')
    # ### end Alembic commands ###
