"""init

Revision ID: 64bf13d5f58c
Revises: 
Create Date: 2025-01-05 01:31:22.010463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64bf13d5f58c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('client_host', sa.String(length=50), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_collect',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=80), nullable=True),
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('content', sa.String(length=2500), nullable=True),
    sa.Column('translation', sa.String(length=2500), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('source_language', sa.String(length=80), nullable=False),
    sa.Column('target_language', sa.String(length=80), nullable=False),
    sa.Column('speech_role_name', sa.String(length=80), nullable=True),
    sa.Column('auto_playing_voice', sa.Integer(), nullable=True),
    sa.Column('playing_voice_speed', sa.String(length=50), nullable=True),
    sa.Column('auto_text_shadow', sa.Integer(), nullable=True),
    sa.Column('auto_pronunciation', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_topic',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=80), nullable=False),
    sa.Column('ai_role', sa.String(length=280), nullable=False),
    sa.Column('my_role', sa.String(length=280), nullable=False),
    sa.Column('topic', sa.String(length=2500), nullable=False),
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('textbook_id', sa.String(length=80), nullable=False),
    sa.Column('category_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('sub_title', sa.String(length=200), nullable=True),
    sa.Column('video', sa.String(length=500), nullable=True),
    sa.Column('srt_text', sa.Text(), nullable=True),
    sa.Column('pic', sa.String(length=500), nullable=True),
    sa.Column('info_cn', sa.Text(), nullable=True),
    sa.Column('info_en', sa.Text(), nullable=True),
    sa.Column('max_score', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('exercise_type', sa.Integer(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('pic', sa.String(length=500), nullable=True),
    sa.Column('main_title', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('audio', sa.String(length=500), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_detail',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('file_path', sa.String(length=150), nullable=False),
    sa.Column('module', sa.String(length=80), nullable=True),
    sa.Column('module_id', sa.String(length=80), nullable=True),
    sa.Column('file_name', sa.String(length=150), nullable=True),
    sa.Column('file_ext', sa.String(length=20), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('textbook_id', sa.String(length=80), nullable=False),
    sa.Column('category_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('sub_title', sa.String(length=200), nullable=True),
    sa.Column('pic', sa.String(length=500), nullable=True),
    sa.Column('feature', sa.Integer(), nullable=True),
    sa.Column('is_audition', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_explain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('explain_content', sa.Text(), nullable=False),
    sa.Column('explain_audio', sa.String(length=500), nullable=True),
    sa.Column('explain_audio_duration', sa.Float(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('isai', sa.Integer(), nullable=True),
    sa.Column('is_edit', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('textbook_id', sa.String(length=80), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('pic', sa.String(length=500), nullable=True),
    sa.Column('gray_pic', sa.String(length=500), nullable=True),
    sa.Column('is_show', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('must', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=200), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('audio', sa.String(length=500), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('sender', sa.String(length=80), nullable=False),
    sa.Column('receiver', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=2500), nullable=False),
    sa.Column('style', sa.String(length=80), nullable=True),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=80), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_grammar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('message_id', sa.String(length=80), nullable=False),
    sa.Column('file_name', sa.String(length=80), nullable=True),
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_session',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Integer(), nullable=True),
    sa.Column('achieved_targets', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_translate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('message_id', sa.String(length=80), nullable=False),
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('source_language', sa.String(length=80), nullable=False),
    sa.Column('target_language', sa.String(length=80), nullable=False),
    sa.Column('source_text', sa.String(length=512), nullable=False),
    sa.Column('target_text', sa.String(length=512), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings_language',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=80), nullable=False),
    sa.Column('full_language', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('full_label', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings_language_example',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=80), nullable=False),
    sa.Column('example', sa.String(length=250), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('locale', sa.String(length=80), nullable=False),
    sa.Column('local_name', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('avatar', sa.String(length=350), nullable=True),
    sa.Column('audio', sa.String(length=350), nullable=True),
    sa.Column('styles', sa.String(length=350), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('text_cn', sa.Text(), nullable=True),
    sa.Column('step', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_dict_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dict_type', sa.String(length=80), nullable=False),
    sa.Column('dict_label', sa.String(length=80), nullable=False),
    sa.Column('dict_value', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_dict_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dict_type', sa.String(length=80), nullable=False),
    sa.Column('dict_name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('content', sa.String(length=2500), nullable=False),
    sa.Column('contact', sa.String(length=250), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info_cn', sa.Text(), nullable=False),
    sa.Column('info_en', sa.Text(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('info_en_audio', sa.String(length=500), nullable=True),
    sa.Column('match_type', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('role_short_name', sa.String(length=100), nullable=True),
    sa.Column('prompt', sa.String(length=1000), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('textbook',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('sub_title', sa.String(length=200), nullable=True),
    sa.Column('dif_level', sa.String(length=50), nullable=False),
    sa.Column('pic', sa.String(length=500), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('total_star_nums', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('textbook_category',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('category_id', sa.String(length=80), nullable=False),
    sa.Column('textbook_id', sa.String(length=80), nullable=False),
    sa.Column('pid', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'category_id')
    )
    op.create_table('topic',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('group_id', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('role_short_name', sa.String(length=80), nullable=False),
    sa.Column('speech_rate', sa.String(length=80), nullable=False),
    sa.Column('topic_bot_name', sa.String(length=580), nullable=False),
    sa.Column('topic_user_name', sa.String(length=580), nullable=False),
    sa.Column('prompt', sa.String(length=2500), nullable=False),
    sa.Column('description', sa.String(length=580), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('created_by_index', 'topic', ['created_by'], unique=False)
    op.create_index('group_id_index', 'topic', ['group_id'], unique=False)
    op.create_table('topic_group',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('topic_id', sa.String(length=80), nullable=False),
    sa.Column('topic_type', sa.String(length=80), nullable=False),
    sa.Column('topic_name', sa.String(length=80), nullable=False),
    sa.Column('main_target_count', sa.Integer(), nullable=False),
    sa.Column('trial_target_count', sa.Integer(), nullable=False),
    sa.Column('main_target_completed_count', sa.Integer(), nullable=False),
    sa.Column('trial_target_completed_count', sa.Integer(), nullable=False),
    sa.Column('completion', sa.Integer(), nullable=False),
    sa.Column('audio_score', sa.Integer(), nullable=True),
    sa.Column('content_score', sa.Integer(), nullable=True),
    sa.Column('suggestion', sa.String(length=2080), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('completed', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_phrase',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.String(length=80), nullable=False),
    sa.Column('phrase', sa.String(length=500), nullable=False),
    sa.Column('phrase_translation', sa.String(length=500), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('topic_id_index', 'topic_phrase', ['topic_id'], unique=False)
    op.create_table('topic_session_relation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.String(length=80), nullable=False),
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('session_id_index', 'topic_session_relation', ['session_id'], unique=False)
    op.create_index('topic_id_index', 'topic_session_relation', ['topic_id'], unique=False)
    op.create_table('topic_target',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('description_translation', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('topic_id_index', 'topic_target', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('topic_id_index', table_name='topic_target')
    op.drop_table('topic_target')
    op.drop_index('topic_id_index', table_name='topic_session_relation')
    op.drop_index('session_id_index', table_name='topic_session_relation')
    op.drop_table('topic_session_relation')
    op.drop_index('topic_id_index', table_name='topic_phrase')
    op.drop_table('topic_phrase')
    op.drop_table('topic_history')
    op.drop_table('topic_group')
    op.drop_index('group_id_index', table_name='topic')
    op.drop_index('created_by_index', table_name='topic')
    op.drop_table('topic')
    op.drop_table('textbook_category')
    op.drop_table('textbook')
    op.drop_table('teacher')
    op.drop_table('task_target')
    op.drop_table('sys_feedback')
    op.drop_table('sys_dict_type')
    op.drop_table('sys_dict_data')
    op.drop_table('sys_cache')
    op.drop_table('step')
    op.drop_table('settings_role')
    op.drop_table('settings_language_example')
    op.drop_table('settings_language')
    op.drop_table('message_translate')
    op.drop_table('message_session')
    op.drop_table('message_grammar')
    op.drop_table('message')
    op.drop_table('lesson_point')
    op.drop_table('lesson_part')
    op.drop_table('lesson_explain')
    op.drop_table('lesson')
    op.drop_table('file_detail')
    op.drop_table('exercise_options')
    op.drop_table('exercise')
    op.drop_table('course')
    op.drop_table('account_topic')
    op.drop_table('account_settings')
    op.drop_table('account_collect')
    op.drop_table('account')
    # ### end Alembic commands ###
