"""update chapter table structure

Revision ID: 6d563d30a313
Revises: 
Create Date: 2025-02-17 20:13:34.528997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6d563d30a313'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chapter')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('book_id', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('audio_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page_no_v2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('duration', mysql.FLOAT(), nullable=True),
    sa.Column('chapter_id_3rd', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('mp3_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('mp3_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('mp3_url_source', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('sort_order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
