"""Add is_teacher and is_student columns

Revision ID: 7b9884d2002e
Revises: a3a2500b8552
Create Date: 2025-05-09 18:26:37.399496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b9884d2002e'
down_revision: Union[str, None] = 'a3a2500b8552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('is_teacher', sa.Integer(), nullable=True, comment='是否是老师'))
    op.add_column('account', sa.Column('is_student', sa.Integer(), nullable=True, comment='是否是学生'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'is_student')
    op.drop_column('account', 'is_teacher')
    # ### end Alembic commands ###
