"""新增表和添加积分字段

Revision ID: 940cc6f8b262
Revises: 2c6cdd02e5b1
Create Date: 2025-03-11 11:28:26.305810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '940cc6f8b262'
down_revision: Union[str, None] = '2c6cdd02e5b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_progress_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='报告唯一标识'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('book_id', sa.String(length=50), nullable=False, comment='书籍ID'),
    sa.Column('lesson_id', sa.Integer(), nullable=True, comment='课程ID'),
    sa.Column('content', sa.String(length=255), nullable=False, comment='学习内容（单词或句子）'),
    sa.Column('content_type', sa.Integer(), nullable=False, comment='类型（0: 单词发音, 1: 单词读, 2: 单词写, 3: 句子）'),
    sa.Column('error_count', sa.Integer(), nullable=True, comment='错误次数（仅对单词的读和写有效）'),
    sa.Column('points', sa.Integer(), nullable=True, comment='积分'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('json_data', sa.JSON(), nullable=True, comment='JSON 数据'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_book_date', 'study_progress_reports', ['user_id', 'book_id', 'lesson_id', 'content_type'], unique=False)
    op.add_column('account', sa.Column('points', sa.Integer(), nullable=True, comment='积分'))
    op.add_column('study_completion_records', sa.Column('points', sa.Integer(), nullable=True, comment='积分'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_completion_records', 'points')
    op.drop_column('account', 'points')
    op.drop_index('idx_user_book_date', table_name='study_progress_reports')
    op.drop_table('study_progress_reports')
    # ### end Alembic commands ###
