"""textbook page updated

Revision ID: 944ce87c2c6f
Revises: 1388bf576eb4
Create Date: 2025-02-17 00:26:25.190609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '944ce87c2c6f'
down_revision: Union[str, None] = '1388bf576eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('textbook_sentences', 'track_text',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('textbook_sentences', 'track_text',
               existing_type=sa.String(length=1500),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
