"""textbook_entity updated

Revision ID: 96084c351f80
Revises: 029e09eb13bd
Create Date: 2025-02-16 13:41:21.400923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '96084c351f80'
down_revision: Union[str, None] = '029e09eb13bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('textbook', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('textbook', sa.Column('version', sa.String(length=100), nullable=False))
    op.add_column('textbook', sa.Column('version_id', sa.Integer(), nullable=False))
    op.add_column('textbook', sa.Column('version_tag', sa.String(length=50), nullable=False))
    op.add_column('textbook', sa.Column('stage', sa.String(length=50), nullable=False))
    op.add_column('textbook', sa.Column('stage_id', sa.Integer(), nullable=False))
    op.add_column('textbook', sa.Column('stage_tag', sa.String(length=50), nullable=False))
    op.add_column('textbook', sa.Column('grade', sa.String(length=50), nullable=False))
    op.add_column('textbook', sa.Column('grade_id', sa.Integer(), nullable=False))
    op.add_column('textbook', sa.Column('grade_tag', sa.String(length=50), nullable=False))
    op.add_column('textbook', sa.Column('term', sa.String(length=50), nullable=False))
    op.add_column('textbook', sa.Column('term_id', sa.Integer(), nullable=False))
    op.add_column('textbook', sa.Column('term_tag', sa.String(length=50), nullable=False))
    op.add_column('textbook', sa.Column('has_content', sa.Integer(), nullable=True))
    op.add_column('textbook', sa.Column('cover', sa.String(length=500), nullable=True))
    op.add_column('textbook', sa.Column('user_name', sa.String(length=100), nullable=True))
    op.drop_column('textbook', 'sort')
    op.drop_column('textbook', 'sub_title')
    op.drop_column('textbook', 'title')
    op.drop_column('textbook', 'total_star_nums')
    op.drop_column('textbook', 'pic')
    op.drop_column('textbook', 'dif_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('textbook', sa.Column('dif_level', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('textbook', sa.Column('pic', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('textbook', sa.Column('total_star_nums', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('textbook', sa.Column('title', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('textbook', sa.Column('sub_title', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('textbook', sa.Column('sort', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('textbook', 'user_name')
    op.drop_column('textbook', 'cover')
    op.drop_column('textbook', 'has_content')
    op.drop_column('textbook', 'term_tag')
    op.drop_column('textbook', 'term_id')
    op.drop_column('textbook', 'term')
    op.drop_column('textbook', 'grade_tag')
    op.drop_column('textbook', 'grade_id')
    op.drop_column('textbook', 'grade')
    op.drop_column('textbook', 'stage_tag')
    op.drop_column('textbook', 'stage_id')
    op.drop_column('textbook', 'stage')
    op.drop_column('textbook', 'version_tag')
    op.drop_column('textbook', 'version_id')
    op.drop_column('textbook', 'version')
    op.drop_column('textbook', 'name')
    # ### end Alembic commands ###
