"""textbook page updated

Revision ID: 98fcc6817f7a
Revises: afa99d2c6bba
Create Date: 2025-02-17 00:19:30.095388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '98fcc6817f7a'
down_revision: Union[str, None] = 'afa99d2c6bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('textbook_sentences', 'id',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('textbook_sentences', 'track_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('textbook_sentences', 'track_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('textbook_sentences', 'id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
