"""lesson updated and lesson_sentences added

Revision ID: 9a954c1fc3e1
Revises: 20ad4ae72919
Create Date: 2025-02-22 13:15:06.292828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a954c1fc3e1'
down_revision: Union[str, None] = '20ad4ae72919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('book_id', sa.String(length=80), nullable=False))
    op.add_column('lesson', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_column('lesson', 'sub_title')
    op.drop_column('lesson', 'icon_url')
    op.drop_column('lesson', 'is_audition')
    op.drop_column('lesson', 'pic')
    op.drop_column('lesson', 'feature')
    op.drop_column('lesson', 'textbook_id')
    op.drop_column('lesson', 'category_id')
    op.drop_column('lesson', 'ext_id')
    op.drop_column('lesson', 'max_score')
    op.drop_column('lesson', 'lesson_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('lesson_id', mysql.VARCHAR(length=80), nullable=False))
    op.add_column('lesson', sa.Column('max_score', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lesson', sa.Column('ext_id', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('lesson', sa.Column('category_id', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('lesson', sa.Column('textbook_id', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('lesson', sa.Column('feature', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lesson', sa.Column('pic', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('lesson', sa.Column('is_audition', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lesson', sa.Column('icon_url', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('lesson', sa.Column('sub_title', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('lesson', 'parent_id')
    op.drop_column('lesson', 'book_id')
    # ### end Alembic commands ###
