"""添加 speak_count

Revision ID: b2738de4dbea
Revises: 
Create Date: 2025-03-13 13:58:04.211379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b2738de4dbea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_completion_records', sa.Column('speak_count', sa.Integer(), nullable=True, comment='开口次数'))
    op.alter_column('study_progress_reports', 'content_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='类型（0: 单词发音, 1: 单词读, 2: 单词写, 3: 单独拼写按钮进去的那边提交, 4:句子）',
               existing_comment='类型（0: 单词发音, 1: 单词读, 2: 单词写, 3: 句子）',
               existing_nullable=False)
    op.drop_index('topic_id_index', table_name='topic_target')
    op.create_index('uq_target_topic_type_seq', 'topic_target', ['topic_id', 'type', 'sequence'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_target_topic_type_seq', table_name='topic_target')
    op.create_index('topic_id_index', 'topic_target', ['topic_id'], unique=False)
    op.alter_column('study_progress_reports', 'content_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='类型（0: 单词发音, 1: 单词读, 2: 单词写, 3: 句子）',
               existing_comment='类型（0: 单词发音, 1: 单词读, 2: 单词写, 3: 单独拼写按钮进去的那边提交, 4:句子）',
               existing_nullable=False)
    op.drop_column('study_completion_records', 'speak_count')
    # ### end Alembic commands ###
