"""添加 chinese audio_url字段

Revision ID: bb78cc2cf6e2
Revises: 3b9f46d7dd9f
Create Date: 2025-03-15 17:40:14.805919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb78cc2cf6e2'
down_revision: Union[str, None] = '3b9f46d7dd9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_progress_reports', sa.Column('chinese', sa.String(length=300), nullable=True, comment='中文翻译'))
    op.add_column('study_progress_reports', sa.Column('audio_url', sa.String(length=300), nullable=True, comment='音频文件路径或 URL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_progress_reports', 'audio_url')
    op.drop_column('study_progress_reports', 'chinese')
    # ### end Alembic commands ###
