"""column length updated

Revision ID: c391a13071ee
Revises: 3f3ea486211d
Create Date: 2025-02-17 22:52:53.811553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c391a13071ee'
down_revision: Union[str, None] = '3f3ea486211d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('textbook_sentences', 'track_genre',
               existing_type=mysql.VARCHAR(length=1200),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('textbook_sentences', 'track_text',
               existing_type=mysql.VARCHAR(length=1500),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('textbook_sentences', 'track_text',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1500),
               existing_nullable=True)
    op.alter_column('textbook_sentences', 'track_genre',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1200),
               existing_nullable=True)
    # ### end Alembic commands ###
