"""add type field to StudyWordProgress2

Revision ID: c41105c75e72
Revises: 40de73aefaa7
Create Date: 2025-03-03 09:16:43.510648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c41105c75e72'
down_revision: Union[str, None] = '40de73aefaa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_word_progress', sa.Column('type', sa.Integer(), nullable=True, comment='类型字段，默认值为1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_word_progress', 'type')
    # ### end Alembic commands ###
