"""添加 study_completion_records

Revision ID: c97e11bffc15
Revises: 36a47b6a2ceb
Create Date: 2025-03-07 13:47:33.062975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c97e11bffc15'
down_revision: Union[str, None] = '36a47b6a2ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_word_progress', 'plan_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               comment='计划ID',
               existing_comment='学习计划ID')
    op.alter_column('study_word_progress', 'last_study_time',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_comment='最后一次学习时间',
               existing_nullable=True)
    op.alter_column('study_word_progress', 'next_review_time',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_comment='下次复习时间（未掌握时有效）',
               existing_nullable=True)
    op.alter_column('study_word_progress', 'type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='单词类型（0=没全部学完模式，1=全部学完三种模式）',
               existing_comment='类型字段，默认值为1',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_word_progress', 'type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='类型字段，默认值为1',
               existing_comment='单词类型（0=没全部学完模式，1=全部学完三种模式）',
               existing_nullable=True)
    op.alter_column('study_word_progress', 'next_review_time',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_comment='下次复习时间（未掌握时有效）',
               existing_nullable=True)
    op.alter_column('study_word_progress', 'last_study_time',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_comment='最后一次学习时间',
               existing_nullable=True)
    op.alter_column('study_word_progress', 'plan_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               comment='学习计划ID',
               existing_comment='计划ID')
    # ### end Alembic commands ###
