"""recreate table

Revision ID: cabd08eba77a
Revises: 
Create Date: 2025-03-01 16:56:31.278632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cabd08eba77a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='记录唯一标识'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('book_id', sa.Integer(), nullable=False, comment='书籍ID'),
    sa.Column('study_date', sa.Date(), nullable=False, comment='学习日期'),
    sa.Column('new_words', sa.Integer(), nullable=True, comment='今日新学单词数'),
    sa.Column('review_words', sa.Integer(), nullable=True, comment='今日复习单词数'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='今日学习时长（分钟）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_word_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('word_id', sa.Integer(), nullable=False, comment='单词ID'),
    sa.Column('book_id', sa.Integer(), nullable=False, comment='书籍ID'),
    sa.Column('learning_count', sa.Integer(), nullable=True, comment='累计学习次数'),
    sa.Column('correct_count', sa.Integer(), nullable=True, comment='正确次数（用户答对次数）'),
    sa.Column('incorrect_count', sa.Integer(), nullable=True, comment='错误次数（用户答错次数）'),
    sa.Column('last_study_time', sa.DateTime(), nullable=True, comment='最后一次学习时间'),
    sa.Column('next_review_time', sa.DateTime(), nullable=True, comment='下次复习时间（未掌握时有效）'),
    sa.Column('memory_stage', sa.Integer(), nullable=True, comment='记忆阶段（0=未学，1=短期记忆，2=长期记忆）'),
    sa.Column('is_mastered', sa.Integer(), nullable=True, comment='是否已掌握（0=未掌握，1=已掌握）'),
    sa.Column('study_date', sa.Date(), nullable=True, comment='学习日期'),
    sa.Column('is_new', sa.Integer(), nullable=True, comment='是否为新学单词（1=新学，0=复习）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_word', 'user_word_progress', ['user_id', 'word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_word', table_name='user_word_progress')
    op.drop_table('user_word_progress')
    op.drop_table('study_records')
    # ### end Alembic commands ###
