"""add study_plans, user_word_progress, and study_records tables

Revision ID: ce8fbc263713
Revises: e1118f303d3a
Create Date: 2025-03-01 15:31:03.364752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8fbc263713'
down_revision: Union[str, None] = 'e1118f303d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
