"""init alembic

Revision ID: d9452ca27e38
Revises: 
Create Date: 2025-03-16 01:26:28.494334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9452ca27e38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_progress_reports', sa.Column('chinese', sa.String(length=300), nullable=True, comment='中文翻译'))
    op.add_column('study_progress_reports', sa.Column('audio_url', sa.String(length=300), nullable=True, comment='音频文件路径或 URL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_progress_reports', 'audio_url')
    op.drop_column('study_progress_reports', 'chinese')
    # ### end Alembic commands ###
