"""Change textbook_id to VARCHAR(80)

Revision ID: d96bf7ee7518
Revises: 0c55b2d5e64b
Create Date: 2025-07-26 21:42:49.269327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd96bf7ee7518'
down_revision: Union[str, None] = '0c55b2d5e64b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'textbook_id',
               existing_type=mysql.BIGINT(),
               type_=sa.String(length=80),
               existing_comment='关联教材ID',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'textbook_id',
               existing_type=sa.String(length=80),
               type_=mysql.BIGINT(),
               existing_comment='关联教材ID',
               existing_nullable=True)
    # ### end Alembic commands ###
