"""修改json_data的类型

Revision ID: daac3e06cc75
Revises: b2738de4dbea
Create Date: 2025-03-13 17:44:42.395730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'daac3e06cc75'
down_revision: Union[str, None] = 'b2738de4dbea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_progress_reports', 'json_data',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               comment='TEXT 数据 的评分数据',
               existing_comment='JSON 数据',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_progress_reports', 'json_data',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               comment='JSON 数据',
               existing_comment='TEXT 数据 的评分数据',
               existing_nullable=True)
    # ### end Alembic commands ###
