"""recreate tables

Revision ID: e1118f303d3a
Revises: 
Create Date: 2025-02-28 23:50:39.388443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e1118f303d3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    op.drop_table('lesson_explain')
    op.drop_table('textbook_category')
    op.drop_table('teacher')
    op.drop_table('lesson_point')
    op.drop_table('lesson_part')
    op.drop_table('step')
    op.drop_table('exercise')
    op.drop_table('exercise_options')
    op.drop_table('exercise_option')
    op.add_column('account_collect', sa.Column('book_id', sa.String(length=80), nullable=True))
    op.add_column('account_collect', sa.Column('word_id', sa.Integer(), nullable=True))
    op.add_column('lesson', sa.Column('book_id', sa.String(length=80), nullable=False))
    op.add_column('lesson', sa.Column('parent_id', sa.String(length=80), nullable=True))
    op.drop_column('lesson', 'pic')
    op.drop_column('lesson', 'category_id')
    op.drop_column('lesson', 'feature')
    op.drop_column('lesson', 'textbook_id')
    op.drop_column('lesson', 'sub_title')
    op.drop_column('lesson', 'max_score')
    op.drop_column('lesson', 'is_audition')
    op.add_column('textbook', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('textbook', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.add_column('textbook', sa.Column('version_type', sa.String(length=50), nullable=False))
    op.add_column('textbook', sa.Column('publisher', sa.String(length=50), nullable=False))
    op.add_column('textbook', sa.Column('grade', sa.String(length=50), nullable=False))
    op.add_column('textbook', sa.Column('term', sa.String(length=50), nullable=False))
    op.add_column('textbook', sa.Column('icon_url', sa.String(length=500), nullable=True))
    op.add_column('textbook', sa.Column('ext_id', sa.String(length=200), nullable=True))
    op.drop_column('textbook', 'pic')
    op.drop_column('textbook', 'dif_level')
    op.drop_column('textbook', 'sort')
    op.drop_column('textbook', 'sub_title')
    op.drop_column('textbook', 'title')
    op.drop_column('textbook', 'total_star_nums')
    op.alter_column('textbook_chapter', 'book_id',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.add_column('words', sa.Column('uk_phonetic', sa.String(length=100), nullable=True, comment='英式音标'))
    op.add_column('words', sa.Column('us_phonetic', sa.String(length=100), nullable=True, comment='美式音标'))
    op.add_column('words', sa.Column('uk_sound_path', sa.String(length=500), nullable=True, comment='英式发音音频路径'))
    op.add_column('words', sa.Column('us_sound_path', sa.String(length=500), nullable=True, comment='美式发音音频路径'))
    op.drop_index('ix_words_word_id', table_name='words')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_words_word_id', 'words', ['word_id'], unique=True)
    op.drop_column('words', 'us_sound_path')
    op.drop_column('words', 'uk_sound_path')
    op.drop_column('words', 'us_phonetic')
    op.drop_column('words', 'uk_phonetic')
    op.alter_column('textbook_chapter', 'book_id',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
    op.add_column('textbook', sa.Column('total_star_nums', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('textbook', sa.Column('title', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('textbook', sa.Column('sub_title', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('textbook', sa.Column('sort', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('textbook', sa.Column('dif_level', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('textbook', sa.Column('pic', mysql.VARCHAR(length=500), nullable=True))
    op.drop_column('textbook', 'ext_id')
    op.drop_column('textbook', 'icon_url')
    op.drop_column('textbook', 'term')
    op.drop_column('textbook', 'grade')
    op.drop_column('textbook', 'publisher')
    op.drop_column('textbook', 'version_type')
    op.drop_column('textbook', 'subject_id')
    op.drop_column('textbook', 'name')
    op.add_column('lesson', sa.Column('is_audition', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('lesson', sa.Column('max_score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('lesson', sa.Column('sub_title', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('lesson', sa.Column('textbook_id', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('lesson', sa.Column('feature', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('lesson', sa.Column('category_id', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('lesson', sa.Column('pic', mysql.VARCHAR(length=500), nullable=True))
    op.drop_column('lesson', 'parent_id')
    op.drop_column('lesson', 'book_id')
    op.drop_column('account_collect', 'word_id')
    op.drop_column('account_collect', 'book_id')
    op.create_table('exercise_option',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('exercise_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('is_correct', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=False),
    sa.Column('audio', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('exercise_options',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('exercise_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('is_correct', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=False),
    sa.Column('audio', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('exercise',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('lesson_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('title', mysql.TEXT(), nullable=False),
    sa.Column('exercise_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sort', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('pic', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('main_title', mysql.TEXT(), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('step',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('text_cn', mysql.TEXT(), nullable=True),
    sa.Column('step', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('lesson_part',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('textbook_id', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('lesson_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('subtitle', mysql.TEXT(), nullable=True),
    sa.Column('pic', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('gray_pic', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('is_show', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('rate', mysql.FLOAT(), nullable=True),
    sa.Column('must', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('lesson_point',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('lesson_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('word', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('meaning', mysql.TEXT(), nullable=False),
    sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('audio', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('teacher',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('avatar', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('lesson_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('role_short_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('prompt', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('language', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('textbook_category',
    sa.Column('id', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('category_id', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('textbook_id', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('pid', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'category_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('lesson_explain',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('lesson_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('teacher_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('explain_content', mysql.TEXT(), nullable=False),
    sa.Column('explain_audio', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('explain_audio_duration', mysql.FLOAT(), nullable=True),
    sa.Column('sort', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('isai', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_edit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('course',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('textbook_id', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('category_id', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('sub_title', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('video', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('srt_text', mysql.TEXT(), nullable=True),
    sa.Column('pic', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('info_cn', mysql.TEXT(), nullable=True),
    sa.Column('info_en', mysql.TEXT(), nullable=True),
    sa.Column('max_score', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
