"""plan_id to id5

Revision ID: e8b111df1457
Revises: 
Create Date: 2025-03-01 16:38:17.294893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b111df1457'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('book_id', sa.Integer(), nullable=False, comment='书籍ID'),
    sa.Column('daily_words', sa.Integer(), nullable=True, comment='计划每天学多少个单词'),
    sa.Column('total_words', sa.Integer(), nullable=True, comment='这本书总共多少单词'),
    sa.Column('total_days', sa.Integer(), nullable=True, comment='总计划天数'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_plans')
    # ### end Alembic commands ###
