"""username added

Revision ID: ec6a356eb64a
Revises: 522255adb2b8
Create Date: 2025-03-30 00:17:16.717765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ec6a356eb64a'
down_revision: Union[str, None] = '522255adb2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('user_name', sa.String(length=100), nullable=True, comment='用户昵称'))
    op.alter_column('study_completion_records', 'type',
               existing_type=mysql.INTEGER(),
               comment='类型（0: 单词, 1: 句子,2.背词计划用了, 3:真正的单词拼写）',
               existing_comment='类型（0: 单词, 1: 句子,2.背词计划用了）',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_completion_records', 'type',
               existing_type=mysql.INTEGER(),
               comment='类型（0: 单词, 1: 句子,2.背词计划用了）',
               existing_comment='类型（0: 单词, 1: 句子,2.背词计划用了, 3:真正的单词拼写）',
               existing_nullable=True)
    op.drop_column('account', 'user_name')
    # ### end Alembic commands ###
