"""words columns extend

Revision ID: ffb22ecd4f82
Revises: 96a240c99f98
Create Date: 2025-02-14 23:17:11.759511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ffb22ecd4f82'
down_revision: Union[str, None] = '96a240c99f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('paraphrase', sa.Text(), nullable=True, comment='单词的详细释义'))
    op.add_column('words', sa.Column('phonics', sa.Text(), nullable=True, comment='单词的自然拼读信息'))
    op.add_column('words', sa.Column('word_tense', sa.Text(), nullable=True, comment='单词的不同词态（如单数、复数、过去式等）'))
    op.add_column('words', sa.Column('example_sentence', sa.Text(), nullable=True, comment='包含该单词的例句'))
    op.add_column('words', sa.Column('phrase', sa.Text(), nullable=True, comment='包含该单词的常见词组'))
    op.add_column('words', sa.Column('synonym', sa.Text(), nullable=True, comment='单词的近义词'))
    op.alter_column('words', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('words', 'word_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='单词唯一标识ID')
    op.alter_column('words', 'lesson_id',
               existing_type=mysql.INTEGER(),
               comment='所属课时ID',
               existing_nullable=False)
    op.alter_column('words', 'book_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='所属书籍ID',
               existing_nullable=False)
    op.alter_column('words', 'word',
               existing_type=mysql.VARCHAR(length=100),
               comment='单词内容',
               existing_nullable=True)
    op.alter_column('words', 'chinese',
               existing_type=mysql.VARCHAR(length=200),
               comment='单词的中文释义',
               existing_nullable=True)
    op.alter_column('words', 'phonetic',
               existing_type=mysql.VARCHAR(length=100),
               comment='单词的音标',
               existing_nullable=True)
    op.alter_column('words', 'sound_path',
               existing_type=mysql.VARCHAR(length=500),
               comment='单词音频文件路径',
               existing_nullable=True)
    op.alter_column('words', 'image_path',
               existing_type=mysql.VARCHAR(length=500),
               comment='单词图片文件路径',
               existing_nullable=True)
    op.alter_column('words', 'has_base',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否包含基础词信息',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('words', 'has_base',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否包含基础词信息',
               existing_nullable=True)
    op.alter_column('words', 'image_path',
               existing_type=mysql.VARCHAR(length=500),
               comment=None,
               existing_comment='单词图片文件路径',
               existing_nullable=True)
    op.alter_column('words', 'sound_path',
               existing_type=mysql.VARCHAR(length=500),
               comment=None,
               existing_comment='单词音频文件路径',
               existing_nullable=True)
    op.alter_column('words', 'phonetic',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='单词的音标',
               existing_nullable=True)
    op.alter_column('words', 'chinese',
               existing_type=mysql.VARCHAR(length=200),
               comment=None,
               existing_comment='单词的中文释义',
               existing_nullable=True)
    op.alter_column('words', 'word',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='单词内容',
               existing_nullable=True)
    op.alter_column('words', 'book_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='所属书籍ID',
               existing_nullable=False)
    op.alter_column('words', 'lesson_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='所属课时ID',
               existing_nullable=False)
    op.alter_column('words', 'word_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='单词唯一标识ID')
    op.alter_column('words', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('words', 'synonym')
    op.drop_column('words', 'phrase')
    op.drop_column('words', 'example_sentence')
    op.drop_column('words', 'word_tense')
    op.drop_column('words', 'phonics')
    op.drop_column('words', 'paraphrase')
    # ### end Alembic commands ###
