-- Create "tasks" table
CREATE TABLE `tasks` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) NULL,
  `updated_at` datetime(3) NULL,
  `deleted_at` datetime(3) NULL,
  `teacher_id` varchar(80) NOT NULL COMMENT "教师ID",
  `title` varchar(200) NOT NULL COMMENT "任务标题",
  `description` text NULL COMMENT "任务描述",
  `task_type` varchar(50) NOT NULL COMMENT "任务类型",
  `subject` varchar(50) NOT NULL COMMENT "所属学科",
  `deadline` datetime(3) NULL COMMENT "截止时间",
  `status` varchar(20) NULL DEFAULT "draft" COMMENT "任务状态",
  `allow_late_submission` bool NULL DEFAULT 0 COMMENT "允许迟交",
  `max_attempts` bigint NULL COMMENT "最大尝试次数",
  `grading_criteria` text NULL COMMENT "评分标准",
  `total_points` bigint NULL DEFAULT 100 COMMENT "总分",
  `attachments` json NULL COMMENT "附件信息",
  `textbook_id` bigint unsigned NULL COMMENT "关联教材ID",
  `lesson_id` bigint unsigned NULL COMMENT "关联教学单元ID",
  PRIMARY KEY (`id`),
  INDEX `idx_tasks_deleted_at` (`deleted_at`),
  INDEX `idx_tasks_lesson_id` (`lesson_id`),
  INDEX `idx_tasks_status` (`status`),
  INDEX `idx_tasks_subject` (`subject`),
  INDEX `idx_tasks_task_type` (`task_type`),
  INDEX `idx_tasks_teacher_id` (`teacher_id`),
  INDEX `idx_tasks_textbook_id` (`textbook_id`)
) CHARSET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
-- Create "task_contents" table
CREATE TABLE `task_contents` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) NULL,
  `updated_at` datetime(3) NULL,
  `deleted_at` datetime(3) NULL,
  `task_id` bigint unsigned NULL COMMENT "所属任务ID",
  `content_type` varchar(50) NULL COMMENT "内容类型（dictation/spelling/...）",
  `generate_mode` varchar(20) NULL DEFAULT "auto" COMMENT "生成模式(auto/manual)",
  `ref_book_id` varchar(50) NULL COMMENT "关联教材ID",
  `ref_lesson_id` bigint NULL COMMENT "关联单元ID",
  `selected_word_ids` json NULL COMMENT "手动选择的单词ID列表",
  `selected_sentence_ids` json NULL COMMENT "手动选择的句子ID列表",
  `points` bigint NULL COMMENT "分值",
  `metadata` json NULL COMMENT "元数据",
  `order_num` bigint NULL COMMENT "排序号",
  PRIMARY KEY (`id`),
  INDEX `idx_task_contents_content_type` (`content_type`),
  INDEX `idx_task_contents_deleted_at` (`deleted_at`),
  INDEX `idx_task_contents_ref_book_id` (`ref_book_id`),
  INDEX `idx_task_contents_ref_lesson_id` (`ref_lesson_id`),
  INDEX `idx_task_contents_task_id` (`task_id`),
  CONSTRAINT `fk_tasks_task_contents` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
) CHARSET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
